CREATE TABLE Teacher
(
  TeacherId BIGINT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(20) NOT NULL,
  LastName VARCHAR(20) NOT NULL
);

CREATE TABLE GroupOfUniversity
(
  GroupId BIGINT PRIMARY KEY AUTO_INCREMENT,
	NumberGroup VARCHAR(8) NOT NULL,
	TeacherId BIGINT,
  FOREIGN KEY(TeacherId) REFERENCES Teacher(TeacherId) ON DELETE CASCADE
);

CREATE TABLE Student
(
	StudentId BIGINT PRIMARY KEY AUTO_INCREMENT,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	GroupId BIGINT,
  FOREIGN KEY (GroupId) REFERENCES GroupOfUniversity (GroupId) ON DELETE CASCADE
);

CREATE TABLE GroupTeacher (
  GroupId BIGINT NOT NULL,
  TeacherId BIGINT NOT NULL,
  FOREIGN KEY (GroupId) REFERENCES GroupOfUniversity (GroupId) ON DELETE CASCADE,
  FOREIGN KEY (TeacherId) REFERENCES Teacher (TeacherId) ON DELETE CASCADE,
  PRIMARY KEY (GroupId, TeacherId)
);
